config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inboxes do
    resources :messages, only: %i[create destroy], module: :inboxes do
      member do
        patch :upvote
      end
    end
  end
 
  
  root 'static_pages#landing_page'
  get 'pricing', to: 'static_pages#pricing'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
  
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
# frozen_string_literal: true

class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { order(created_at: :desc) }, dependent: :destroy, inverse_of: :inbox
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 3..500 }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :inbox, counter_cache: true
  belongs_to :user

  validates :body, presence: true
  validates :body, length: { in: 3..300 }

  acts_as_votable

  def upvote!(user)
    if user.voted_up_on? self, vote_scope: 'like'
      unvote_by user, vote_scope: 'like'
    else
      upvote_by user, vote_scope: 'like'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :inboxes, dependent: :destroy
  has_many :messages, dependent: :destroy

  acts_as_voter
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/inboxes/messages_controller.rb
# frozen_string_literal: true

module Inboxes
  class MessagesController < ApplicationController
    before_action :set_inbox

    def upvote
      @message = @inbox.messages.find(params[:id])
      @message.upvote! current_user
      redirect_to @inbox
    end

    def create
      
      @message = @inbox.messages.new(message_params)

      respond_to do |format|
        if @message.save
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update('new_message',
                                  partial: 'inboxes/messages/form',
                                  locals: { message: Message.new }),
              turbo_stream.update('message_counter', @inbox.messages_count),
              turbo_stream.prepend('message_list', partial: 'inboxes/messages/message',
                                                   locals: { message: @message })
            ]
          end
          format.html { redirect_to @inbox, notice: 'Message was successfully created.' }
        else
          format.turbo_stream do
            render turbo_stream:
            turbo_stream.update('new_message',
                                partial: 'inboxes/messages/form',
                                locals: { message: @message })
          end
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @message = @inbox.messages.find(params[:id])
      @message.destroy

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove(@message),
            turbo_stream.update('message_counter', @inbox.messages_count)
          ]
        end
        format.html { redirect_to @inbox, notice: 'Message was successfully destroyed.' }
      end
    end

    private

    def set_inbox
      @inbox = Inbox.find(params[:inbox_id])
    end

    def message_params
      params.require(:message).permit(:body).merge(user: current_user)
    end
  end
end

app/controllers/inboxes_controller.rb
# frozen_string_literal: true

class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[show edit update destroy]
  before_action :authorize_inbox, only: %i[edit update destroy]

  def index
    #@inboxes = Inbox.all
    @q = Inbox.ransack(params[:q])
    @inboxes = @q.result(distinct: true).order(created_at: :desc)

  end

  def show; end

  def new
    @inbox = Inbox.new
  end

  def edit; end

  def create
    @inbox = current_user.inboxes.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inbox.destroy
    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: 'Inbox was successfully destroyed.' }
    end
  end

  private

  def authorize_inbox
    authorize @inbox
  end

  def set_inbox
    @inbox = Inbox.find(params[:id])
  end

  def inbox_params
    params.require(:inbox).permit(:name, :theme_color)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def landing_page; end

  def pricing; end

  def privacy; end

  def terms; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/inboxes_helper.rb
# frozen_string_literal: true

module InboxesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox) do |form| %>
  <%= render "shared/errors", form: form %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
        <%= form.color_field :theme_color %>
  </div>

  <div>
    <%= form.submit %>

  </div>
<% end %>

app/views/inboxes/_inbox.html.erb
<div id="<%= dom_id inbox %>" style = "color:<%= inbox.theme_color%>;" >
  
  <h3>
    <%= link_to inbox.name.capitalize, inbox %>
  </h3>

  Messages:
  <%= inbox.messages_count %>
  <p>
  
  </p>
  <h4>
  Сreated by:
  <%= inbox.user.email %>
  Date:
  <%= inbox.created_at.strftime("%d.%b.%Y %H:%M")%>
  </h4>

</div>

app/views/inboxes/edit.html.erb
<h1>Editing inbox</h1>

<%= render "form", inbox: @inbox %>

<hr>

<div>
  <%= link_to "Show this inbox", @inbox %> |
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/index.html.erb
<h2><%= link_to "New inbox", new_inbox_path %></h2>


<h3>Inboxes:<%= @inboxes.count %></h3>
<%= sort_link(@q, :name, default_order: :desc) %>
<%= sort_link(@q, :created_at, default_order: :desc) %>
<%= sort_link(@q, :messages_count, default_order: :desc) %>


<div id="inboxes">
  <% @inboxes.each do |inbox| %>
    <%= render inbox %>
    <hr>
  <% end %>
</div>

app/views/inboxes/messages/_form.html.erb
<%= form_with(model: [@inbox, message]) do |form| %>
  <%= render "shared/errors", form: form %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/messages/_message.html.erb
<div id="<%= dom_id message %>">

  <p>
    <strong>User:</strong>
    <%= message.user.email %>
  </p>

  <p>
    <strong>Message:</strong>
     <%= simple_format(message.body) %>
  </p>


  <%= button_to "Like", [:upvote, @inbox, message],
          method: :patch,
          data: {turbo: "false"} %>
          
  <%= message.cached_votes_total %>
  

  

  <%= button_to "Destroy", inbox_message_path(@inbox, message), method: :delete %>

</div>

app/views/inboxes/new.html.erb
<h1>New inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/show.html.erb
<%= render @inbox %>

<div class = "box">
  <%= link_to "Edit", edit_inbox_path(@inbox) if policy(@inbox).edit? %>
  <%= button_to "Destroy", @inbox, method: :delete if policy(@inbox).destroy? %>

  <%= link_to "Back", inboxes_path %>
</div>

 <h3>
  Messages:
  <span id = "message_counter" >
    <%= @inbox.messages_count %>
  </span>
 </h3>

<div id = "new_message">
  <%= render "inboxes/messages/form", message: Message.new %>
</div>

<div id = "message_list" >
  <%= render partial: 'inboxes/messages/message', collection: @inbox.messages %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.application.class.module_parent.name %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 
   
  

  <body>
    <div class = "container">
      <div class = "header">
      <%= render "/shared/navigation" %>
      </div>
      <%= render "/shared/flash" %>
      <%= yield %>
      <%= render "/shared/footer" %>
    </div>
  </body>

  
     
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Body:</strong>
    <%= simple_format(message.body) %>
  </p>

  <p>
    <strong>Inbox:</strong>
    <%= link_to message.inbox.name, message.inbox %>
  </p>

  <p>
    <strong>User:</strong>
    <%= message.user.email %>
  </p>

</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/shared/_errors.html.erb
<div class = "errors">
  <% if form.object.errors.any? %>
        <h4><%= pluralize(form.object.errors.count, "error") %> prohibited this message from being saved:</h4>
        <ul>
          <% form.object.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
    <% end %>
  </div>

app/views/shared/_flash.html.erb
<div class = "flash">
    <% flash.each do |key, value| %>
        <%= content_tag :div, value, id: "#{key}" %>
    <% end %>

</div>

app/views/shared/_footer.html.erb
<div class = "footer">
<hr>
    <%= link_to_unless_current "Pricing", pricing_path %>
    <%= link_to_unless_current "Terms", terms_path %>
    <%= link_to_unless_current "Privacy", privacy_path %>
</div>

app/views/shared/_navigation.html.erb
<div>
    <div class = "logo">
        <%= link_to_unless_current Rails.application.class.module_parent.name, root_path %>
    </div>

    <div class = "nav">
        <% if signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path %>

        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
        <% else %>
            <%= link_to "Log in", new_user_session_path %>
            <%= link_to "Register", new_user_registration_path %>
        <% end %>
    </div>

</div>

app/views/static_pages/landing_page.html.erb
<h1>StaticPages#landing_page</h1>
<p>Find me in app/views/static_pages/landing_page.html.erb</p>
<h2>
<%= link_to_unless_current "Inboxes", inboxes_path %>
</h2>

app/views/static_pages/pricing.html.erb
<h1>StaticPages#pricing</h1>
<p>Find me in app/views/static_pages/pricing.html.erb</p>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/terms.html.erb
<h1>StaticPages#terms</h1>
<p>Find me in app/views/static_pages/terms.html.erb</p>